name: Build Release APK

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew assembleRelease --no-daemon
    - name: Sign APK
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
        keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "33.0.2"
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Release APK
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
